[package]
name = "ssh_bookmarker"
version = "0.1.0"
authors = ["Andreas Fuchs <asf@stripe.com>"]

[dependencies]
docopt = "0.6"
rustc-serialize = "0.3"  # if you're using `derive(RustcDecodable)`
quick-error = "1.1.0"
